apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/component: api-gateway
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: grupo04-kong
    app.kubernetes.io/part-of: grupo04
  annotations:
    argocd.argoproj.io/sync-wave: "4"
configMapGenerator:
  - name: grupo04-kong-config
    files:
      - kong.yml=kong.yml
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
