apiVersion: v1
kind: Service
metadata:
  name: grupo04-kong-proxy
  labels:
    app.kubernetes.io/name: grupo04-kong
    app.kubernetes.io/part-of: grupo04
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grupo04-kong
  ports:
    - name: http
      port: 80
      targetPort: proxy
      protocol: TCP
    - name: https
      port: 443
      targetPort: proxy-ssl
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: grupo04-kong-admin
  labels:
    app.kubernetes.io/name: grupo04-kong
    app.kubernetes.io/part-of: grupo04
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grupo04-kong
  ports:
    - name: admin
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: status
      port: 8100
      targetPort: status
      protocol: TCP
