apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-service
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chat-service.inf326.cl
      secretName: chat-service-inf326-cl-tls
  rules:
    - host: chat-service.inf326.cl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-service
                port:
                  number: 80
