apiVersion: v1
kind: Service
metadata:
  name: messages-service
  labels:
    app.kubernetes.io/name: messages-service
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  selector:
    app.kubernetes.io/name: messages-service
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
