apiVersion: apps/v1
kind: Deployment
metadata:
  name: grupo04-interfaz
  labels:
    app: grupo04-interfaz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grupo04-interfaz
  template:
    metadata:
      labels:
        app: grupo04-interfaz
    spec:
      containers:
        - name: interfaz
          image: registry.kroder.dev/utfsm/interfaz:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: PORT
              value: "8000"
          command: ["python"]
          args: ["manage.py", "runserver", "0.0.0.0:8000"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
