apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grupo04-interfaz
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chat-grupo04.inf326.nursoft.dev
      secretName: chat-grupo04-inf326-nursoft-dev-tls
    - hosts:
        - chat-utfsm.kroder.dev
      secretName: chat-utfsm-kroder-dev-tls
  rules:
    - host: chat-grupo04.inf326.nursoft.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grupo04-interfaz
                port:
                  number: 80
    - host: chat-utfsm.kroder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grupo04-interfaz
                port:
                  number: 80
