apiVersion: v1
kind: Service
metadata:
  name: grupo04-interfaz
  labels:
    app: grupo04-interfaz
spec:
  selector:
    app: grupo04-interfaz
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
