apiVersion: v1
kind: Service
metadata:
  name: interfaz
  labels:
    app: interfaz
spec:
  selector:
    app: interfaz
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
